export const calendars = [
    {
        id: 1,
        date: '2023-11-15',
        morning: ['Tín', 'Huy'],
        afternoon: ['Tín', 'Anh'],
        evening: ['Huy', 'Anh'],
    },
    {
        id: 2,
        date: '2023-11-17',
        morning: ['Tín', 'Huy'],
        afternoon: ['Tín', 'Anh'],
        evening: ['Huy', 'Anh'],
    },
    {
        id: 3,
        date: '2023-11-18',
        morning: ['Tín', 'Huy'],
        afternoon: ['Tín', 'Anh'],
        evening: ['Huy', 'Anh'],
    },
    {
        id: 4,
        date: '2023-11-19',
        morning: ['Tín', 'Huy'],
        afternoon: ['Tín', 'Anh'],
        evening: ['Huy', 'Anh'],
    },
    {
        id: 5,
        date: '2023-11-20',
        morning: ['Tín', 'Huy'],
        afternoon: ['Tín', 'Anh'],
        evening: ['Huy', 'Anh'],
    },
    {
        id: 6,
        date: '2023-11-21',
        morning: ['Tín', 'Linh'],
        afternoon: ['Huy', 'Anh', 'Linh'],
        evening: ['Linh',],
    },
    {
        id: 7,
        date: '2023-11-22',
        morning: ['Tín', 'Huy'],
        afternoon: ['Tín', 'Anh'],
        evening: ['Huy', 'Anh'],
    },
    {
        id: 8,
        date: '2023-11-23',
        morning: ['Tín', 'Huy'],
        afternoon: ['Tín', 'Anh'],
        evening: ['Huy', 'Anh'],
    },
    {
        id: 9,
        date: '2023-11-24',
        morning: ['Tín', 'Huy'],
        afternoon: ['Tín', 'Anh'],
        evening: ['Huy', 'Anh'],
    },
    {
        id: 10,
        date: '2023-11-25',
        morning: ['Tín', 'Huy'],
        afternoon: ['Tín', 'Anh'],
        evening: ['Huy', 'Anh'],
    },
    {
        id: 11,
        date: '2023-11-26',
        morning: ['Tín', 'Huy'],
        afternoon: ['Tín', 'Anh'],
        evening: ['Huy', 'Anh'],
    },
    {
        id: 12,
        date: '2023-11-27',
        morning: ['Tín', 'Huy'],
        afternoon: ['Tín', 'Anh'],
        evening: ['Huy', 'Anh'],
    },
    {
        id: 13,
        date: '2023-11-28',
        morning: ['Tín', 'Huy'],
        afternoon: ['Tín', 'Anh'],
        evening: ['Huy', 'Anh'],
    },
]