const bills = [
    {
        id: 'b1',
        number: 1,
        staff_cashier: 'Nguyễn Văn A',
        status: 1,
        time_in: '2023-01-25 07:13:00',
        time_out: '2023-01-25 09:22:00',
        payment: 10000,
        foods: [
            {
                id: 'f1',
                name: 'Bò hầm rau củ kiểu Pháp',
                type: 'Món chính',
                price: 1000,
                image: 'https://fujifoods.vn/wp-content/uploads/2021/12/bo-ham-nam-1.jpg',
                quantity_sold: 1200,
                quantity: 1,
                status: 'đang',
                node: '',
            },
            {
                id: 'f2',
                name: 'Salad đậu đen Mexico',
                type: 'Khai vị',
                price: 1000,
                image: 'https://hrv.com.vn/wp-content/uploads/2021/04/salad-bo-kieu-mexico-mon-an-tot-cho-suc-khoe-va-ngon-mieng-guacamole2.jpg',
                quantity_sold: 1500,
                quantity: 1,
                status: 'chưa',
                node: '',
            },
        ],
    },
    {
        id: 'b2',
        number: 2,
        staff_cashier: 'Nguyễn Văn A',
        status: 1,
        time_in: '2023-02-25 07:13:00',
        time_out: '2023-02-25 09:22:00',
        payment: 10000,
        foods: [
            {
                id: 'f1',
                name: 'Bò hầm rau củ kiểu Pháp',
                type: 'Món chính',
                price: 1300,
                image: 'https://fujifoods.vn/wp-content/uploads/2021/12/bo-ham-nam-1.jpg',
                quantity_sold: 1200,
                quantity: 1,
                status: 'đang',
                node: '',
            },
            {
                id: 'f2',
                name: 'Salad đậu đen Mexico',
                type: 'Khai vị',
                price: 1000,
                image: 'https://hrv.com.vn/wp-content/uploads/2021/04/salad-bo-kieu-mexico-mon-an-tot-cho-suc-khoe-va-ngon-mieng-guacamole2.jpg',
                quantity_sold: 1500,
                quantity: 2,
                status: 'chưa',
                node: '',
            },
            {
                id: 'f3',
                name: 'Bò hầm rau củ kiểu Pháp',
                type: 'Món chính',
                price: 1000,
                image: 'https://fujifoods.vn/wp-content/uploads/2021/12/bo-ham-nam-1.jpg',
                quantity_sold: 1200,
                quantity: 1,
                status: 'đang',
                node: '',
            },
            {
                id: 'f4',
                name: 'Salad đậu đen Mexico',
                type: 'Khai vị',
                price: 1200,
                image: 'https://hrv.com.vn/wp-content/uploads/2021/04/salad-bo-kieu-mexico-mon-an-tot-cho-suc-khoe-va-ngon-mieng-guacamole2.jpg',
                quantity_sold: 1500,
                quantity: 1,
                status: 'chưa',
                node: '',
            },
            {
                id: 'f5',
                name: 'Bò hầm rau củ kiểu Pháp',
                type: 'Món chính',
                price: 1000,
                image: 'https://fujifoods.vn/wp-content/uploads/2021/12/bo-ham-nam-1.jpg',
                quantity_sold: 1200,
                quantity: 1,
                status: 'đang',
                node: '',
            },
            {
                id: 'f6',
                name: 'Salad đậu đen Mexico',
                type: 'Khai vị',
                price: 1000,
                image: 'https://hrv.com.vn/wp-content/uploads/2021/04/salad-bo-kieu-mexico-mon-an-tot-cho-suc-khoe-va-ngon-mieng-guacamole2.jpg',
                quantity_sold: 1500,
                quantity: 1,
                status: 'chưa',
                node: '',
            },
            {
                id: 'f7',
                name: 'Bò hầm rau củ kiểu Pháp',
                type: 'Món chính',
                price: 1000,
                image: 'https://fujifoods.vn/wp-content/uploads/2021/12/bo-ham-nam-1.jpg',
                quantity_sold: 1200,
                quantity: 1,
                status: 'đang',
                node: '',
            },
            {
                id: 'f8',
                name: 'Salad đậu đen Mexico',
                type: 'Khai vị',
                price: 1000,
                image: 'https://hrv.com.vn/wp-content/uploads/2021/04/salad-bo-kieu-mexico-mon-an-tot-cho-suc-khoe-va-ngon-mieng-guacamole2.jpg',
                quantity_sold: 1500,
                quantity: 1,
                status: 'chưa',
                node: '',
            },
        ],
    },
    {
        id: 'b3',
        number: 4,
        staff_cashier: 'Nguyễn Văn A',
        status: 2,
        time_in: '2023-09-25 07:13:00',
        time_out: '',
        payment: 0,
        foods: [
            {
                id: 'f1',
                name: 'Bò hầm rau củ kiểu Pháp',
                type: 'Món chính',
                price: 1000,
                image: 'https://fujifoods.vn/wp-content/uploads/2021/12/bo-ham-nam-1.jpg',
                quantity_sold: 1200,
                quantity: 1,
                status: 'đang',
                node: '',
            },
            {
                id: 'f2',
                name: 'Salad đậu đen Mexico',
                type: 'Khai vị',
                price: 1000,
                image: 'https://hrv.com.vn/wp-content/uploads/2021/04/salad-bo-kieu-mexico-mon-an-tot-cho-suc-khoe-va-ngon-mieng-guacamole2.jpg',
                quantity_sold: 1500,
                quantity: 1,
                status: 'chưa',
                node: '',
            },
        ],
    },
];

export { bills };
